# Generated by Django 3.1.8 on 2022-04-30 21:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='price',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='end_time',
            field=models.TimeField(validators=[api.models.max_time]),
        ),
        migrations.AlterField(
            model_name='module',
            name='start_time',
            field=models.TimeField(validators=[api.models.min_time]),
        ),
    ]
