# Generated by Django 3.1.8 on 2022-05-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_module_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='assignature',
        ),
        migrations.AlterField(
            model_name='module',
            name='reservation_bool',
            field=models.BooleanField(default=False),
        ),
    ]
