# Generated by Django 3.1.8 on 2022-05-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation'),
        ('api', '0003_institution'),
    ]

    operations = [
    ]
