# Generated by Django 3.1.8 on 2022-05-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_module_price'),
        ('api', '0004_merge_20220524_1646'),
    ]

    operations = [
    ]
