# Generated by Django 3.1.8 on 2022-05-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220524_2147'),
        ('api', '0005_merge_20220524_1703'),
    ]

    operations = [
    ]
