# Generated by Django 3.1.8 on 2022-05-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20220524_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
